---
apiVersion: v1
kind: Service
metadata:
  name: downlink-service
spec:
  ports:
    - port: 8000
      nodePort: 31111
      targetPort: main-port
      protocol: TCP
  selector:
    app: downlink
  type: LoadBalancer
