---
apiVersion: v1
kind: Pod
metadata:
    name: api.czekmaet.com
    labels:
        app: dockerdemo
spec:
    containers:
        - name: docker-demo
          image: sariabod/docker-demo
          ports:
              - containerPort: 8000
